### ISSUE TITLE
Artifact checking requires login 

### ISSUE THREAD

**Issue by scompt** [JakeWharton/sdk-artifact-sync#2]
We're running Artifactory and deploying the artifacts works great (thanks for the script BTW). However, when I run a second time, the artifacts are all uploaded again because the script is unable to check for their existence because our Artifactory requires you to be logged in to fetch the artifacts. 

The way I see it, there are a couple solutions:
1. Use Maven somehow to check for the existence of the artifacts. I'm not crazy about this because I didn't find anything that worked immediately without needing a pom and plugins and because it'll be slow as hell because Maven.
2. Parse settings.xml to get the login credentials and add these to the HEAD request that's made.
3. Make an Artifactory version that just uses the Artifactory API and doesn't deal with Maven at all.

@JakeWharton Which option do you think would have the best chance of getting merged? Any other ideas?

**Comment by JakeWharton** [comment]
I think this is a dupe of #1. I would prefer 2 since I don't actually use
Artifactory!

**Comment by scompt** [comment]
Yeah, you're right. I missed the authentication part in the comment there. I'll close this and add my fix to that issue.

**Comment by scompt** [comment]
I ended up modifying an [existing bash script](https://www.jfrog.com/blog/artifactory-command-line-interface-cli-pure-and-simple/) to use the Artifactory API. You can find the gist [here](https://gist.github.com/scompt/e0002bb90cc0ccc2ed265ae4c9470b05)
