### ISSUE TITLE
I still have to accept licenses

### ISSUE THREAD

**Issue by emartynov** [JakeWharton/sdk-artifact-sync#4]
With android gradle plugin 2.2.2 I see the message:
```
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 23.0.3, Android SDK Platform 24].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```
So looks like uploading to Nexus and disabling local repositories is not enough to have successful build on clean jenkins node.

Any suggestion?

**Comment by JakeWharton** [comment]
Those SDK components are not maven dependencies so they have nothing to do with what this script is trying to accomplish.

**Comment by emartynov** [comment]
Thanks! Clear!

So we still need manually/automated install sdk with build and sdk tools. Or use your android sdk plugin or rely on new android gradle plugin autodownload.

This script is replacing downloading of maven repositories through android sdk manager.

**Comment by JakeWharton** [comment]
Correct. The Gradle plugin also has built in support for downloading these
SDK components which is what that error message is indicating. You have to
write out/copy a license file from your computer to your CI machine to have
it work automatically.

**Comment by emartynov** [comment]
I added, it even wrote [article](https://medium.com/@jack_martynov/one-auto-download-android-dependencies-evening-1f492147b4fd#.838dakken) (which I need to correct).

But I run in a nightmare with lint - it fails on CI and works on my local machine. So the error is that CI is using lint 24.2.2 and locally it runs with 25.2.2.

I need a clean virtual machine to check if android plugin downloads tools, or it relies on that Gradle loads it from maven repo.

I also have some Gradle plugins that depend on Android build tools. And of course, they depend on way older version of that we are using now.

I also didn't find how to force Gradle script dependencies. How even to check classpath of Gradle script.
